
@baseUrl = http://localhost:5254/api





GET {{baseUrl}}/flights
Accept: application/json


@flightId = {{getFlights.response.body.$[0].id}}





GET {{baseUrl}}/flights/{{flightId}}
Accept: application/json






POST {{baseUrl}}/passengers
Content-Type: application/json

{
  "fullName": "Иван Иванов (Обычный)",
  "passportNumber": "1111 111111",
  "isVip": false
}


@normalUserId = {{createNormalUser.response.body.id}}






POST {{baseUrl}}/passengers
Content-Type: application/json

{
  "fullName": "Даня Кострыкин (VIP)",
  "passportNumber": "7777 777777",
  "isVip": true
}


@vipUserId = {{createVipUser.response.body.id}}






POST {{baseUrl}}/tickets/buy
Content-Type: application/json

{
  "flightId": "{{flightId}}",
  "passengerId": "{{normalUserId}}",
  "bookingClass": "Economy",
  "paymentAmount": 8000
}


@normalTicketId = {{buyNormalTicket.response.body.id}}





POST {{baseUrl}}/tickets/buy
Content-Type: application/json

{
  "flightId": "{{flightId}}",
  "passengerId": "{{vipUserId}}",
  "bookingClass": "Business",
  "paymentAmount": 21600
}

@vipTicketId = {{buyVipTicket.response.body.id}}





POST {{baseUrl}}/tickets/checkin
Content-Type: application/json

{
  "ticketId": "{{normalTicketId}}",
  "seatNumber": "1A"
}




POST {{baseUrl}}/tickets/checkin
Content-Type: application/json

{
  "ticketId": "{{vipTicketId}}",
  "seatNumber": "1A"
}





GET {{baseUrl}}/flights/{{flightId}}/passengers
Accept: application/json