
@baseUrl = http://localhost:5254/api







POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "danya_admin",
  "password": "airport_2026"
}


@adminToken = {{loginAdmin.response.body.token}}



POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "petya_buyer",
  "password": "123"
}



POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "petya_buyer",
  "password": "123"
}


@userToken = {{loginUser.response.body.token}}








GET {{baseUrl}}/flights
Accept: application/json


@flightId = {{getFlights.response.body.$[0].id}}








POST {{baseUrl}}/passengers
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "fullName": "Иван Иванов (Обычный)",
  "passportNumber": "1111 111111",
  "isVip": false
}


@normalUserId = {{createNormalUser.response.body.id}}



POST {{baseUrl}}/passengers
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "fullName": "Петр Петров (Бизнес, не VIP)",
  "passportNumber": "2222 222222",
  "isVip": false
}


@businessUserId = {{createBusinessUser.response.body.id}}



POST {{baseUrl}}/passengers
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "fullName": "Даня Кострыкин (VIP)",
  "passportNumber": "7777 777777",
  "isVip": true
}


@vipUserId = {{createVipUser.response.body.id}}








POST {{baseUrl}}/tickets/buy
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "flightId": "{{flightId}}",
  "passengerId": "{{normalUserId}}",
  "bookingClass": "Economy",
  "paymentAmount": 8000
}


@normalTicketId = {{buyNormalTicket.response.body.id}}



POST {{baseUrl}}/tickets/buy
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "flightId": "{{flightId}}",
  "passengerId": "{{businessUserId}}",
  "bookingClass": "Business",
  "paymentAmount": 24000
}


@businessTicketId = {{buyBusinessTicket.response.body.id}}



POST {{baseUrl}}/tickets/buy
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "flightId": "{{flightId}}",
  "passengerId": "{{vipUserId}}",
  "bookingClass": "Business",
  "paymentAmount": 21600
}


@vipTicketId = {{buyVipTicket.response.body.id}}








POST {{baseUrl}}/tickets/checkin
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "ticketId": "{{normalTicketId}}",
  "seatNumber": "1A"
}


POST {{baseUrl}}/tickets/checkin
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "ticketId": "{{normalTicketId}}",
  "seatNumber": "10A"
}


POST {{baseUrl}}/tickets/checkin
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "ticketId": "{{businessTicketId}}",
  "seatNumber": "1A"
}


POST {{baseUrl}}/tickets/checkin
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "ticketId": "{{vipTicketId}}",
  "seatNumber": "1A"
}








GET {{baseUrl}}/flights/{{flightId}}/passengers
Authorization: Bearer {{userToken}}
Accept: application/json



GET {{baseUrl}}/flights/{{flightId}}/passengers
Authorization: Bearer {{adminToken}}
Accept: application/json



DELETE {{baseUrl}}/tickets/checkin/{{normalTicketId}}
Authorization: Bearer {{adminToken}}
